### ISSUE TITLE
undefined method `environment' for nil:NilClass when importing Bootstrap

### ISSUE THREAD

**Issue by edoardoo** [tommyblue/Rubyfatt#69]
appena installato da questo errore. 
Per risolvere portare la gemma sass-rails a 4.0.5.

**Comment by tommyblue** [comment]
sei su `master` o `develop`?

**Comment by edoardoo** [comment]
Master

Edoardo Odorico - from mobile
Edoardoo.com

**Comment by tommyblue** [comment]
ok, la `develop` è molto diversa da `master` in questo momento. Puoi fare una pull request per le modifiche?

**Comment by edoardoo** [comment]
Yup

Edoardo Odorico - from mobile
Edoardoo.com

**Comment by tommyblue** [comment]
L'errore a cui fai riferimento è questo: https://github.com/rails/sass-rails/issues/191
